server:
  port: 8080

spring:
  application:
    name: acme-salary-management
  datasource:
    url: jdbc:h2:mem:salarydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true

# ACME App properties
acme:
  salary:
    seed-on-startup: true
    seed-count: 10000
